runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: django
  version: latest
- name: ssl
  version: latest

builtins:
- remote_api: on

manual_scaling:
  instances: 1

handlers:
- url: /.*
  script: main.app
  secure: always

